### ISSUE TITLE
CPUs nr bigger with 2

### ISSUE THREAD

**Issue by DaPa** [hrk/no-frills-cpu-classic#1]
Small bug counting the nr of cpu cores: for example for a dual-core was trying to set cpu0, 1, 2 and 3. Because last two don't exist on my minix x5 board, the "SU".waitFor was returning 1, which made it complain with err_update_failed... even the other two cpus were actually updated fine (and same time a su toast also appeared saying that the no frills cpu classic has been granted superuser permission, which created confusion). 

The fix should be in src/it/sineo/android/noFrillsCPUClassic/extra/SysUtils.java::setFrequenciesAndGovernor: increment after break, and make the for loop only for smaller not equal:

```
            while (true) {
                File f = new File(SysUtils.scaling_min_freq.replace("cpu0", "cpu" + cpus));
                if (!f.exists()) {
                    break;
                }
                cpus++;
            }
            for (int i = 0; i < cpus; i++) {
```

**Comment by hrk** [comment]
Thank you very much, I'll fix it and try to update the app.
